# Generated by Django 5.1.14 on 2025-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, help_text='Immediate/2 weeks/1 month', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='Aviation certifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Recruiter company name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(blank=True, help_text='Company website', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_job_title',
            field=models.CharField(blank=True, help_text='Preferred job title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_location',
            field=models.CharField(blank=True, help_text='Preferred work location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('recruiter', 'Recruiter'), ('job_seeker', 'Job Seeker'), ('user', 'User'), ('viewer', 'Viewer')], default='user', max_length=20),
        ),
    ]
