# Generated by Django 5.1.14 on 2025-11-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_availability_userprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_recruiter',
            field=models.BooleanField(default=False, help_text='Admin-verified recruiter status'),
        ),
    ]
