# Generated by Django 5.2.8 on 2025-11-19 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('normalized_name', models.TextField(unique=True)),
                ('operation_type', models.CharField(blank=True, choices=[('business', 'Business'), ('scheduled', 'Scheduled'), ('low_cost', 'Low Cost'), ('ad_hoc_charter', 'Ad-hoc Charter'), ('cargo', 'Cargo')], max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_mapping',
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('run_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('items_found', models.IntegerField(default=0)),
                ('items_inserted', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawl_log',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('normalized_title', models.TextField(blank=True, null=True)),
                ('company', models.TextField()),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('operation_type', models.CharField(blank=True, choices=[('business', 'Business'), ('scheduled', 'Scheduled'), ('low_cost', 'Low Cost'), ('ad_hoc_charter', 'Ad-hoc Charter'), ('cargo', 'Cargo')], max_length=20, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('retrieved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('removed', 'Removed')], default='active', max_length=20)),
                ('senior_flag', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['normalized_title'], name='jobs_normali_0858bc_idx'), models.Index(fields=['company'], name='jobs_company_8219f2_idx'), models.Index(fields=['posted_date'], name='jobs_posted__bbd299_idx')],
            },
        ),
    ]
