# Generated by Django 5.2.8 on 2025-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_normali_0858bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_company_8219f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_posted__bbd299_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='is_senior_position',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymapping',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('scheduled', 'Scheduled'), ('low_cost', 'Low Cost'), ('ad_hoc_charter', 'Ad-hoc Charter'), ('cargo', 'Cargo'), ('Passenger', 'Passenger')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('scheduled', 'Scheduled'), ('low_cost', 'Low Cost'), ('ad_hoc_charter', 'Ad-hoc Charter'), ('cargo', 'Cargo'), ('Passenger', 'Passenger')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='senior_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('removed', 'Removed'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['normalized_title', 'company'], name='jobs_normali_96956f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'posted_date'], name='jobs_status_a8a3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['country_code', 'operation_type'], name='jobs_country_6a70aa_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_created_7c32a5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['senior_flag', 'status'], name='jobs_senior__305c96_idx'),
        ),
    ]
