# Generated by Django 5.2.8 on 2025-11-21 10:02

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    """Create UserProfile for all users that don't have one"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('jobs', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={'role': 'user'}
        )


def reverse_func(apps, schema_editor):
    """No need to reverse - profiles can stay"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, reverse_func),
    ]
