# Generated by Django 5.2.8 on 2025-11-21 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_optimize_models_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymapping',
            options={'ordering': ['-total_jobs', 'company_name']},
        ),
        migrations.AlterModelOptions(
            name='crawllog',
            options={'ordering': ['-run_time']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_normali_96956f_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_status_a8a3d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_country_6a70aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_created_7c32a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_senior__305c96_idx',
        ),
        migrations.AlterField(
            model_name='companymapping',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('scheduled', 'Scheduled'), ('low_cost', 'Low Cost'), ('ad_hoc_charter', 'Ad-hoc Charter'), ('cargo', 'Cargo'), ('passenger', 'Passenger')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companymapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crawllog',
            name='run_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['normalized_title'], name='jobs_norm_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('url', ''), _negated=True), name='jobs_url_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('company', ''), _negated=True), name='jobs_company_not_empty'),
        ),
    ]
