# Generated by Django 5.1.14 on 2025-11-24 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_companymapping_options_alter_crawllog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_enabled', models.BooleanField(default=False, help_text='🔴 MASTER SWITCH: Enable/disable ALL automated scheduling. When OFF, no scheduled tasks will run (scrapers, reports, alerts, etc.)')),
                ('scraper_schedule_enabled', models.BooleanField(default=True, help_text='Enable twice-daily automated scraping (00:00 and 12:00 UTC)')),
                ('job_expiry_enabled', models.BooleanField(default=True, help_text='Automatically mark old jobs as expired')),
                ('job_expiry_days', models.IntegerField(default=30, help_text='Number of days before a job is marked as expired (default: 30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('daily_reports_enabled', models.BooleanField(default=False, help_text='Generate and email daily CSV reports at 23:00 UTC')),
                ('weekly_reports_enabled', models.BooleanField(default=False, help_text='Generate and email weekly summary reports (Sunday 09:00 UTC)')),
                ('report_email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses for reports (e.g., admin@example.com, team@example.com)')),
                ('senior_role_alerts_enabled', models.BooleanField(default=False, help_text='Send email alerts when new senior roles are found')),
                ('health_check_alerts_enabled', models.BooleanField(default=True, help_text='Send alerts if scrapers fail or data issues detected')),
                ('alert_email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses for alerts (e.g., ops@example.com)')),
                ('scraper_run_times', models.CharField(default='0:00,12:00', help_text='Comma-separated times in HH:MM format (24-hour UTC). Example: 0:00,12:00 for midnight and noon', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Schedule Configuration',
                'verbose_name_plural': 'Schedule Configuration',
                'db_table': 'schedule_config',
            },
        ),
    ]
