# Generated by Django 5.1.14 on 2025-11-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_schedule_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
