# Generated by Django 5.1.14 on 2025-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymapping',
            name='auto_created',
            field=models.BooleanField(db_index=True, default=False, help_text='Automatically created by scraper'),
        ),
        migrations.AddField(
            model_name='companymapping',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=True, help_text='Needs manual review and verification'),
        ),
        migrations.AddField(
            model_name='companymapping',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this mapping was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='companymapping',
            name='reviewed_by',
            field=models.CharField(blank=True, help_text='Username who reviewed this mapping', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymapping',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('passenger', '✈️ Passenger Airlines'), ('cargo', '📦 Cargo & Freight'), ('business', '🎩 Business & Private Aviation'), ('scheduled', '🗓️ Scheduled Operations'), ('low_cost', '💺 Low-Cost Carrier'), ('ad_hoc_charter', '🛩️ Charter & On-Demand'), ('helicopter', '🚁 Helicopter Operations'), ('mro', '🔧 Maintenance & Repair'), ('ground_ops', '🏢 Ground Operations'), ('atc', '🎯 Air Traffic Control')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('passenger', '✈️ Passenger Airlines'), ('cargo', '📦 Cargo & Freight'), ('business', '🎩 Business & Private Aviation'), ('scheduled', '🗓️ Scheduled Operations'), ('low_cost', '💺 Low-Cost Carrier'), ('ad_hoc_charter', '🛩️ Charter & On-Demand'), ('helicopter', '🚁 Helicopter Operations'), ('mro', '🔧 Maintenance & Repair'), ('ground_ops', '🏢 Ground Operations'), ('atc', '🎯 Air Traffic Control')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', '✨ New'), ('active', '🟢 Active'), ('reviewed', '✓ Reviewed'), ('expired', '⏰ Expired'), ('archived', '📦 Archived'), ('closed', '🔒 Closed')], db_index=True, default='new', max_length=20),
        ),
    ]
