# Generated by Django 5.1.14 on 2025-11-26 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_add_company_mapping_review_fields'),
        ('resumes', '0002_alter_resume_options_resume_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Review'), ('reviewing', '👀 Under Review'), ('shortlisted', '⭐ Shortlisted'), ('interview_scheduled', '📅 Interview Scheduled'), ('interviewed', '✓ Interviewed'), ('offer_sent', '📧 Offer Sent'), ('accepted', '✅ Accepted'), ('rejected', '❌ Rejected'), ('withdrawn', '🚫 Withdrawn')], db_index=True, default='pending', max_length=30)),
                ('cover_letter', models.TextField(blank=True, help_text='Applicant cover letter', null=True)),
                ('applicant_notes', models.TextField(blank=True, help_text='Additional notes from applicant', null=True)),
                ('recruiter_notes', models.TextField(blank=True, help_text='Internal notes from recruiter', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When application was reviewed', null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='Rating from 1-5', null=True)),
                ('interview_date', models.DateTimeField(blank=True, help_text='Scheduled interview date', null=True)),
                ('interview_notes', models.TextField(blank=True, help_text='Interview notes', null=True)),
                ('applied_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When application was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_device', models.CharField(blank=True, help_text='mobile/desktop/tablet', max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Applicant IP address', null=True)),
                ('applicant', models.ForeignKey(help_text='User who applied', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job being applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, help_text='Resume used for application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Recruiter who reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status', '-applied_at'], name='app_status_date_idx'), models.Index(fields=['applicant', '-applied_at'], name='app_user_date_idx'), models.Index(fields=['job', '-applied_at'], name='app_job_date_idx'), models.Index(fields=['reviewed_by', '-reviewed_at'], name='app_reviewer_idx'), models.Index(fields=['-applied_at'], name='app_date_desc_idx')],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('job', models.ForeignKey(help_text='Viewed job', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['job', '-viewed_at'], name='view_job_date_idx'), models.Index(fields=['-viewed_at'], name='view_date_desc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job', null=True)),
                ('job', models.ForeignKey(help_text='Saved job', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('user', models.ForeignKey(help_text='User who saved the job', on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_jobs',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='saved_user_date_idx')],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
