# Generated by Django 5.2.8 on 2025-11-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobapplication_jobview_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='senior_override',
            field=models.BooleanField(null=True, blank=True, db_index=True),
        ),
    ]
