# Generated by Django 5.2.8 on 2025-12-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_add_posted_by_to_job'),
        ('resumes', '0002_alter_resume_options_resume_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(help_text='Recruiter who shortlisted', on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_candidates', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(help_text='Resume shortlisted', on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='resumes.resume')),
            ],
            options={
                'db_table': 'shortlisted_candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recruiter', '-created_at'], name='shortlist_recruiter_idx')],
                'unique_together': {('recruiter', 'resume')},
            },
        ),
    ]
