# Generated by Django 5.2.8 on 2025-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('aviation', models.JSONField(blank=True, default=dict)),
                ('experience', models.JSONField(blank=True, default=dict)),
                ('total_score', models.FloatField(default=0.0)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('file_content', models.TextField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
