# Generated by Django 5.1.14 on 2025-11-26 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Currently active/looking for jobs'),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible to recruiters'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Job seeker who owns this resume', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='total_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-created_at'], name='resume_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['-total_score', 'is_public'], name='resume_score_public_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['is_active', 'is_public', '-total_score'], name='resume_active_idx'),
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resumes',
        ),
    ]
